### ISSUE TITLE
What to do with the other files?

### ISSUE THREAD

**Issue by mhkeller** [lexithium/sublime-aml-highlighter#2]
The readme says to put `aml.tmLanguage` in the User packages folder. Should the `tmLanguages` and `tmPreferences` file also be dragged into there?

Thanks for making this btw! Very useful!

**Comment by lexithium** [comment]
Those other files are only necessary if you plan on making changes to code for the syntax highlighter yourself. `aml.tmLanguage` is all that's necessary if you only want to implement the highlighter in Sumblime.

Glad someone else other than from my team is using this thing!

**Comment by mhkeller** [comment]
Got it. Thanks!
